/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"

#include "serial.h"
#include "init.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int io_test(void)
{
	//enable the clock
	enable_clocks();

	//initialise_board
	initialise_board();

	// Set the callback function to be called when the button is press (PA0)
	// When button is pressed, chase_led() will be invoked
	setting_callback(&chase_led);

	// enable the interrupt for the button
	enable_interrupt();

    /* Loop forever */
	for(;;) {}
}

int main(void) {
//    test_serial();
	test_serial_interrupt();

    /* Loop forever */
	for(;;);
}
